import Head from "next/head";
import Image from "next/image";
import HorizontalScroller from "../components/HorizontalScroller";
import MainHero from "../components/MainHero";
import Navbar from "../components/Navbar";
import SideSocialBar from "../components/SideSocialBar";
import styles from "../styles/Home.module.css";

import { ImAirplane } from "react-icons/im";
import { GiSubmarine, GiMeepleArmy, GiElectric } from "react-icons/gi";
import { FaCar, FaHandHoldingMedical } from "react-icons/fa";
import { BsCameraReelsFill } from "react-icons/bs";
import { RiBuilding2Fill } from "react-icons/ri";

import { gsap } from "gsap";
import { ScrollTrigger } from "gsap/dist/ScrollTrigger";
import { useEffect, useRef } from "react";

export default function Home() {
	const aboutheadingRef = useRef(null);
	const aboutHeadingTrigger = useRef(null);

	// useEffect(() => {
	// 	gsap.to(aboutheadingRef.current, {
	// 		x: 500,
	// 		duration: 2,
	// 		ease: "bounce",
	// 		scrollTrigger: {
	// 			trigger: aboutHeadingTrigger,
	// 			markers: true,
	// 			start: "top center",
	// 		},
	// 	});
	// }, []);

	gsap.registerPlugin(ScrollTrigger);
	const aboutheader = useRef(null);
	const aboutDesc = useRef(null);
	const dynoPic = useRef(null);
	const industriesCardsContainer = useRef(null);

	useEffect(() => {
		gsap.to("#aboutheader", {
			x: 0,
			duration: 0.75,
			ease: "ease-in",
			scrollTrigger: {
				trigger: "#aboutContainer",
				start: "top center",
				end: "bottom top",
				toggleActions: "play none none reset",
			},
		});

		gsap.to(aboutDesc.current, {
			opacity: 1,
			duration: 0.75,
			scrollTrigger: {
				trigger: "#aboutContainer",
				start: "top center",
				end: "bottom top",
				toggleActions: "play none none reset",
			},
		});

		gsap.to(dynoPic.current, {
			scale: 1,
			duration: 0.75,
			scrollTrigger: {
				trigger: "#industriesContainer",
				start: "top center",
				end: "bottom top",
				toggleActions: "play none none reset",
			},
		});

		gsap.to(industriesCardsContainer.current, {
			x: 0,
			duration: 0.75,

			scrollTrigger: {
				trigger: "#industriesContainer",
				start: "top center",
				end: "bottom top",
				toggleActions: "play none none reset",
			},
		});
	}, []);

	return (
		<div className="bg-[#010101]">
			<Head>
				<title>Omegaverse</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<SideSocialBar />
				<MainHero />
			</main>

			<section className="flex w-screen justify-center min-h-auto md:min-h-[70vh] items-center bg-[#010101]">
				<div className="flex flex-col md:flex-row max-w-[90vw] md:max-w-[80vw] h-full justify-center items-center">
					{/* <div className="md:flex-1 hidden">
						<Image
							src="/img/home/Machine.png"
							alt="Twitter Button"
							width={800}
							height={720}
						/>
					</div> */}
					<div
						className="flex-1 justify-center items-center h-full relative "
						id="aboutContainer"
					>
						<div className="md:w-[70%] w-full">
							<h1
								className="text-[#FF6600] mb-8 translate-x-[-600px]  sHeading"
								id="aboutheader"
								ref={aboutheader}
							>
								About Omega
							</h1>
							<p
								className="text-white pText pb-8 opacity-0"
								ref={aboutDesc}
								id="#aboutDesc"
							>
								We are a large scale CNC & 3D printing, composites start up. We
								manufacture tooling, models, prototypes and patterns for
								numerous sectors. We support local initiatives that drive
								awareness and create innovation through re-purposing waste. We
								are passionate about sustainability, our economy and
								competitiveness as a country
							</p>
						</div>
					</div>
				</div>
			</section>

			<section
				className="flex w-full justify-center bg-no-repeat min-h-[100vh] items-center bg-cover bg-center relative "
				id="industriesContainer"
			>
				<div className="h-full max-w-[90vw] md:max-w-[80vw] flex flex-col md:flex-row gap-10">
					<div className="text-white flex-1">
						<h1 className="sHeading mb-16">Industries We Serve</h1>
						<div
							className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-3 gap-4 translate-x-[600px]"
							ref={industriesCardsContainer}
						>
							<div className="border border-[#FF6600] flex flex-col items-center justify-center p-5">
								<GiSubmarine size={50} className="p-1 mb-2" />
								<span className="pText mr-4 text-[#FF6600]">Marine</span>
							</div>
							<div className="border border-[#FF6600] flex flex-col items-center justify-center p-5">
								<BsCameraReelsFill size={50} className="p-1 mb-2" />
								<span className="pText mr-4 text-[#FF6600]">Film</span>
							</div>
							<div className="border border-[#FF6600] flex flex-col items-center justify-center p-5">
								<FaCar size={50} className="p-1 mb-2" />
								<span className="pText mr-4 text-[#FF6600]">Automotive</span>
							</div>
							{/* <div className="border border-[#FF6600] flex flex-col items-center justify-center p-5">
								<FaHandHoldingMedical size={50} className="p-1 mb-2" />
								<span className="pText mr-4 text-[#FF6600]">Medical</span>
							</div> */}
							<div className="border border-[#FF6600] flex flex-col items-center justify-center p-5">
								<ImAirplane size={50} className="p-1 mb-2" />
								<span className="pText mr-4 text-[#FF6600]">Aerospace</span>
							</div>
							<div className="border border-[#FF6600] flex flex-col items-center justify-center p-5">
								<GiMeepleArmy size={50} className="p-1 mb-2" />
								<span className="pText mr-4 text-[#FF6600]">Military</span>
							</div>
							{/* <div className="border border-[#FF6600] flex flex-col items-center justify-center p-5">
								<GiElectric size={50} className="p-1 mb-2" />
								<span className="pText mr-4 text-[#FF6600]">Electronics</span>
							</div> */}
							<div className="border border-[#FF6600] flex flex-col items-center justify-center p-5">
								<RiBuilding2Fill size={50} className="p-1 mb-2" />
								<span className="pText mr-4 text-[#FF6600]">Architectural</span>
							</div>
						</div>
						<ul className="">
							<li></li>
							<li>
								<span className="pText mr-4 text-[#FF6600]"></span>
							</li>
							<li>
								<span className="pText mr-4 text-[#FF6600]"></span>
							</li>
							<li>
								<span className="pText mr-4 text-[#FF6600]"></span>
							</li>
							<li>
								<span className="pText mr-4 text-[#FF6600]"></span>
							</li>
							<li>
								<span className="pText mr-4 text-[#FF6600]"></span>
							</li>
						</ul>
					</div>
					<div className="w-full flex-1">
						<img
							src="/img/home/dyno.png"
							alt="Main Pic"
							ref={dynoPic}
							className="scale-[3]"
						/>
					</div>
				</div>
			</section>

			<section className="relative">
				<HorizontalScroller />
			</section>
		</div>
	);
}
